"""Added user table and updated consumer and chef models

Revision ID: b7069aa43621
Revises: 
Create Date: 2024-08-06 16:46:31.268206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7069aa43621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')
        batch_op.drop_column('username')
        batch_op.drop_column('email')

    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.drop_index('consumer_email')
        batch_op.drop_index('consumer_username')
        batch_op.drop_column('consumer_email')
        batch_op.drop_column('consumer_username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('consumer_username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('consumer_email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_index('consumer_username', ['consumer_username'], unique=True)
        batch_op.create_index('consumer_email', ['consumer_email'], unique=True)

    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
